### ISSUE TITLE
Minor: fixation points misplaced when two screens not the same dimensions

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#13]
Hi Dee,
On this line you use `w`:

https://github.com/dcnieho/Titta/blob/master/Titta.m#L1259

which is set in a previous loop (line #1173) to be the second screen, when you are drawing these points to the first screen. Easiest way to test is set second screen to be windowed (i.e. `[0 0 1000 1000]`), and you'll see the drawing on the first screen constrained to [1000 1000]...

Off-topic but I'm amazed how smooth the dual screen stuff is, I've developed a double-buffered animated movie calibration object (good for baby and animal calibration) for Titta and it works with dual screens flawlessly, no frames dropped...

**Comment by dcnieho** [comment]
Thanks for reporting!

**Comment by iandol** [comment]
Thanks for fixing! 👍

**Comment by iandol** [comment]
@dcnieho -- I notice there are still some problems when you draw the calibration results on the second display if it isn't the same size:

![Screenshot from 2020-03-02 12-54-42](https://user-images.githubusercontent.com/153905/75646626-33f01800-5c85-11ea-8e07-dc2730a5a675.png)

**Comment by dcnieho** [comment]
Hmm, I'm pretty sure that this is "by design" (the logic of that screen is
to have everything 1:1, so the visualized validation errors are directly
interpretable), but now think that that makes little sense when working
with a second monitor, very little. Will fix, probably next week.

**Comment by dcnieho** [comment]
Pff, this was thorny. But now hopefully fixed properly. Let me know @iandol if you have a chance to test!
