### ISSUE TITLE
Minor: Font name misspelt

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#3]
Hi this is minor, but in Titta.m, the font `'Segoe UI'` is misspelt...

e.g. https://github.com/dcnieho/Titta/blob/master/Titta.m#L751

Off topic but your calibration interface is very beautiful! 😎

**Comment by dcnieho** [comment]
Thanks for the kind words, glad you like it! Keep these comments going, much appreciated, no matter how small :)
