### ISSUE TITLE
drawLiveData called with wrong parameters from readMeTwoScreens demo

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#31]
Hi Dee,

In readmeTwoScreens.m the drawLiveDemo function is called like so:

```matlab
drawLiveData(wpntO,EThndl.buffer,500,settings.freq,eyeColors{:},4,winRectO(3:4));
```

But these parameters aren't matched to the function itself:

```matlab
function drawLiveData(wpnt,eyeData,dataWindowLength,clrL,clrR,pointSz,scrRes,sFac,offset)
```

Also when this demo crashes, the catch statement doesn't call EThndl.deInit(); so the connection stays open, you could add something like:

```matlab
    if exist('EThndl','var') && isa(EThndl,'Titta');
        EThndl.deInit();
    end
```

**Comment by dcnieho** [comment]
Thanks for the report! Will look into it, which will be a while. I lean
towards not adding the deinit upon crash, as it may well be interesting to
see the state the eye tracker was in when it crashed (last message, data,
etc)
