### ISSUE TITLE
Reference to non-existant field 'RMS'

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#35]
Hi Dee, sorry this is not going to be a well fleshed out issue as I am away from the lab and Titta doesn't support my travel laptop (macOS system). My staff report there is a `Reference to non-existant field 'RMS'` error on line 3250 (getDataQuality) of Titta. The stack trace shows it comes during a manual calibration. I assume this is related to this change: https://github.com/dcnieho/Titta/commit/3a432a946f2b338c511527f5bd1da7d4d35049f8

![image](https://user-images.githubusercontent.com/153905/146372220-6996afb6-4d0c-41d4-9a20-0ee3f75f1fa6.png)

**Comment by dcnieho** [comment]
thanks for the report! I forgot to rename some variables it seems... Fixed
