### ISSUE TITLE
1.10 API Support

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#37]
1.10.1 of the SDK is available:

https://developer.tobiipro.com/tobiiprosdk/whatsnew.html

They have added a new data stream (eye openness), but for whatever reason, they have removed Octave support 😡 I think it makes sense to make sure there is a release tag or clear version so we can keep using 1.9 API Titta version?

**Comment by dcnieho** [comment]
Well, I'm not using their matlab package, so their dropping of Octave
support will not affect Titta. If i drop support for something, i will
indeed make a release tag (like i have now for the last version with 32-bit
support).

1.10 support is being working on, I have something already that merges the
eye openness into the gaze stream (if enabled), which is where it belongs i
think. To be tested more and hopefully released next week
