### ISSUE TITLE
how to deal with error 201?

### ISSUE THREAD

**Issue by TH0420** [dcnieho/Titta#44]
I failed to finalized the recording,because the error 201.

TalkToProLab: Command 'FinalizeRecording' returned an error: 201 (Recording finalization failed): There is a gap in the timeline between adjacent stimulus events

titta seems fill the gap with empty interval filler automaticly，but I failed. how to deal with this problem？

**Comment by dcnieho** [comment]
You do not provide enough details. TalkToProLab's `finalizeRecording` function, as used in [the demo](https://github.com/dcnieho/Titta/blob/master/demos/readmeProLabIntegration.m) fills these gaps automatically, so this error should not occur. Are you using my TalkToProLab? Is your code similar to my demo. And in the first place, does my demo work for you?
